api:
  image: nuvla/api
  tag: 5.22.0
  # Comma separated list of Elasticsearch endpoints.
  es_endpoints: es
  # Super user password.
  super_password: "supeR8-supeR8"

ui:
  image: nuvla/ui
  tag: 2.26.2

job:
  image: nuvla/job
  tag: 2.18.0

zk:
  image: zookeeper
  tag: 3.4

es:
  image: nuvla/es
  tag: 7.11.1.0

# Comma separated list of Zookeeper endpoints.
zk_endpoints: zk:2181

traefik:
  image: traefik
  tag: 1.7-alpine
