# FIXME: nuvla/api:5.{6,7}.0 fail to add super user.
api:
  image: nuvladev/api
  tag: master

ui:
  image: nuvla/ui
  tag: 2.12.0

job:
  image: nuvla/job
  tag: 2.10.0

zk:
  image: zookeeper
  tag: 3.4

es:
  image: nuvla/es
  tag: 7.7.0.0

traefik:
  image: traefik
  tag: 1.7-alpine
