---
apiVersion: v1
kind: Service
metadata:
  name: es
  labels:
    app: nuvla
spec:
  ports:
    - port: 9200
      targetPort: 9200
      name: http
  selector:
    app: es
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    app: es
spec:
  selector:
    matchLabels:
      app: es
  replicas: {{ .Values.es.replicas }}
  serviceName: "es"
  template:
    metadata:
      labels:
        app: es
      annotations:
        description: Elasticsearch for Nuvla
        tags: db
    spec:
      restartPolicy: Always
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: take-data-dir-ownership
        image: alpine:3
        command:
          - chown
          - -R
          - 1000:1000
          - /usr/share/elasticsearch/data
        volumeMounts:
          - name: es-data
            mountPath: /usr/share/elasticsearch/data
      containers:
        - name: es
          image: {{ .Values.es.image }}:{{ .Values.es.tag }}
          resources:
            requests:
              cpu: "750m"
              memory: "2Gi"
            limits:
              cpu: "1000m"
              memory: "2.5Gi"
          env:
            - name: cluster.name
              value: elasticsearch
            - name: xpack.security.enabled
              value: "false"
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms2g -Xmx2g"
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-data
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.es.pvc.storageClass }}
      resources:
        requests:
          storage: {{ .Values.es.pvc.size }}
