apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data
  labels:
    app: es-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.es.pvc.size }}
  storageClassName: {{ .Values.es.pvc.storageClass }}
