apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nuvla
  annotations:
    kubernetes.io/ingress.class: "traefik"
    ingress.kubernetes.io/custom-request-headers: "nuvla-authn-info:"
spec:
  rules:
    - http:
        paths:
          - path: /api
            backend:
              serviceName: api
              servicePort: 8200
          - path: /ui
            backend:
              serviceName: ui
              servicePort: 80
          - path: /
            backend:
              serviceName: ui
              servicePort: 80
