# Comma separated list of Zookeeper endpoints.
zk_endpoints: zk.nuvla-zk:2181

# Kafka bootstrap servers.
kafka_endpoints: kafka-kafka-bootstrap.nuvla-kafka:9092

# Comma separated list of Elasticsearch endpoints.
es_endpoints: es.nuvla-es

api:
  image: nuvla/api
  tag: 5.23.2
  replicas: 1
  # Super user password.
  super_password: "supeR8-supeR8"
  env:
    ES_SNIFFER_INIT: "yes"
    KAFKA_PRODUCER_INIT: "yes"

ui:
  image: nuvla/ui
  tag: 2.28.0
  replicas: 1
  config:
    file_path: "secrets/ui-config.json"
    secret_name: "ui-config"

job:
  image: nuvla/job
  tag: 2.18.0
  replicas_distributor: 1
  replicas_executor: 2

traefik:
  image: traefik
  tag: 1.7-alpine
  # Service type to expose Nuvla on the cluster (LoadBalancer or NodePort).
  service_type: LoadBalancer

session:
  secret_name: session-secrets
  crt_file_path: "secrets/session.crt"
  key_file_path: "secrets/session.key"

logging:
  config_name: "log4j-properties"
  file_path: "assets/log4j.properties"

