apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nuvla
  namespace: {{ .Release.Namespace }}
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    ingress.kubernetes.io/custom-request-headers: "nuvla-authn-info:"
spec:
  ingressClassName: traefik
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 8200
          - path: /ui
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui
                port:
                  number: 80
