---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: {{ .Release.Namespace }}
data:
  traefik.yaml: |
    entryPoints:
      web:
        address: :80
        http:
          redirections:
            entryPoint:
              to: websecure
              scheme: https
      websecure:
        address: ":443"
        http:
          middlewares:
            traefik-compress:
              compress:
    providers:
      kubernetesIngress:
        allowEmptyServices: true
        namespaces:
          - {{ .Release.Namespace }}
      file:
        filename: /config/dynamic.yaml
    accessLog:
      addInternals: true
    log:
      level: INFO
    api:
      dashboard: true
      insecure: true
      debug: true
  dynamic.yaml: |
    http:
      routers:
        catchall:
          # attached only to web entryPoint
          entryPoints:
            - "websecure"
          # catchall rule
          rule: "PathPrefix(`/`)"
          service: unavailable
          tls: {}
          # lowest possible priority
          # evaluated when no other router is matched
          priority: 1
      services:
        # Service that will always answer a 503 Service Unavailable response
        unavailable:
          loadBalancer:
            servers: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
      annotations:
        description: Traefik as ingress controller for Nuvla.
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-config
            items:
              - key: "traefik.yaml"
                path: "traefik.yaml"
              - key: "dynamic.yaml"
                path: "dynamic.yaml"
      containers:
      - name: traefik-ingress-lb
        image: {{ .Values.traefik.image }}:{{ .Values.traefik.tag }}
        volumeMounts:
          - mountPath: "/config/traefik.yaml"
            name: "config"
            subPath: "traefik.yaml"
            readOnly: true
          - mountPath: "/config/dynamic.yaml"
            name: "config"
            subPath: "dynamic.yaml"
            readOnly: true
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --configFile=/config/traefik.yaml
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --entrypoints.https.http.tls
        - --providers.kubernetesingress
        - --log.level=DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
