---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: {{ .Release.Namespace }}
data:
  traefik.yaml: |
    entryPoints:
      http:
        address: :80
        http:
          redirections:
            entryPoint:
              to: https
              scheme: https
      https:
        address: :443
    providers:
      kubernetesIngress: {}
    accessLog: {}
    api:
      dashboard: true
      insecure: true
      debug: true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik-ingress-controller
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: traefik-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: traefik-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: traefik-ingress-lb
        name: traefik-ingress-lb
      annotations:
        description: Traefik as ingress controller for Nuvla.
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
        - name: config
          configMap:
            name: traefik-config
            items:
              - key: "traefik.yaml"
                path: "traefik.yaml"
      containers:
      - name: traefik-ingress-lb
        image: {{ .Values.traefik.image }}:{{ .Values.traefik.tag }}
        volumeMounts:
          - mountPath: "/config"
            name: "config"
            readOnly: true
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8080
        args:
        - --configFile=/config/traefik.yaml
        - --entrypoints.http.address=:80
        - --entrypoints.https.address=:443
        - --entrypoints.https.http.tls
        - --providers.kubernetesingress
        - --log.level=DEBUG
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    k8s-app: traefik-ingress-lb
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      name: http
    - protocol: TCP
      port: 443
      name: https
    - protocol: TCP
      port: 8080
      name: admin
