---
# Secret manifest containing ID and key for pre-provisioned subvolume.
apiVersion: v1
kind: Secret
metadata:
  name: rook-ceph-csi
  namespace: nuvla
data:
  # admin in base64
  userID: <CHANGE_ME_ID>
  # admin's secret used to mount the cephfs volume. base64 of key from `ceph auth get client.admin`.
  userKey: <CHANGE_ME_KEY>
