---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.logging.config_name }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=Will be set by Helm.
binaryData:
  "log4j.properties": |-
    {{ .Files.Get .Values.logging.file_path | b64enc | indent 2 }}
