---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.session.secret_name }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=Will be set by Helm.
type: Opaque
data:
  "session.crt": |-
    {{ .Files.Get .Values.session.crt_file_path | b64enc | indent 2 }}
  "session.key": |-
    {{ .Files.Get .Values.session.key_file_path | b64enc | indent 2 }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ui.config.secret_name }}
  annotations:
    checkov.io/skip1: CKV_K8S_21=Will be set by Helm.
type: Opaque
data:
  "config.json": |-
  {{ .Files.Get .Values.ui.config.file_path | b64enc | indent 2 }}
