---
apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: nuvla
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: ui
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  labels:
    app: nuvla
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
      annotations:
        description: Nuvla UI static content
        tags: ui
    spec:
      restartPolicy: Always
      containers:
        - name: ui
          image: {{ .Values.ui.image }}:{{ .Values.ui.tag }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "50Mi"
            limits:
              cpu: "200m"
              memory: "100Mi"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: {{ .Values.ui.config.secret_name }}
              mountPath: "/usr/share/nginx/html/ui/config/config.json"
              subPath: config.json
              readOnly: true
      volumes:
        - name: {{ .Values.ui.config.secret_name }}
          secret:
            secretName: {{ .Values.ui.config.secret_name }}
